INSERT
	INTO
	SHOP_ITEMS.ITEMS
(ITEM_ID,
	ITEM_NAME,
	STOCK,
	UNIT_PRICE,
	CREATE_AT)
VALUES('ITM-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ITEMS_PK.NEXTVAL, 6, '0'), 'Monitor', 50 , 500000 , SYSDATE);


INSERT
	INTO
	SHOP_ITEMS.ITEMS
(ITEM_ID,
	ITEM_NAME,
	STOCK,
	UNIT_PRICE,
	CREATE_AT)
VALUES('ITM-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ITEMS_PK.NEXTVAL, 6, '0'), 'Keyboard', 150 , 150000 , SYSDATE);


INSERT
	INTO
	SHOP_ITEMS.ITEMS
(ITEM_ID,
	ITEM_NAME,
	STOCK,
	UNIT_PRICE,
	CREATE_AT)
VALUES('ITM-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ITEMS_PK.NEXTVAL, 6, '0'), 'Mouse', 200 , 120000 , SYSDATE);
